# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  crmeducacional:
    image: crmeducacional
    build:
      context: .
      dockerfile: CRM-Educacional/Dockerfile
    ports:
      - 3001:3001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
